### PR TITLE
 Fixes ClassCastException on RedBlackTree operations (#2098)

### LINKED ISSUE #2098: ClassCastException in RedBlackTree operations
I've stumbled on a bug in the implementation of `RedBlackTree`, which results in an occasional `ClassCastException` when calling methods like `intersection` or `difference`. In particular, the following test throws:
```
final RedBlackTree<Integer> t1 =
        RedBlackTree.ofAll(Integer::compare, Vector.of(1462193440, 0,
                2147483647, -2147483648, 0, 637669539, -1612766076, -1, 1795938819, 1,
                0, -420800448, -2147483648, 497885405, 0, 1084073832, 1, 1439964148,
                1961646330));
final RedBlackTree<Integer> t2 =
        RedBlackTree.ofAll(Integer::compare, Vector.of(-1, 1, 2147483647,
                -1434983536, -2147483648, -1452486079, 1365799971, 231691980,
                -1780534767, -2147483648, 1448658704, 0, 1526591298));
final RedBlackTree<Integer> t3 =
        RedBlackTree.ofAll(Integer::compare, Vector.of(-1188825722, -582974613));
assertThat(t1.intersection(t2).intersection(t3).isEmpty());
```
```
java.lang.ClassCastException: io.vavr.collection.RedBlackTreeModule$Empty cannot be cast to io.vavr.collection.RedBlackTreeModule$Node

	at io.vavr.collection.RedBlackTreeModule$Node.joinGT(RedBlackTree.java:703)
	at io.vavr.collection.RedBlackTreeModule$Node.joinGT(RedBlackTree.java:703)
	at io.vavr.collection.RedBlackTreeModule$Node.join(RedBlackTree.java:692)
	at io.vavr.collection.RedBlackTreeModule$Node.split(RedBlackTree.java:802)
	at io.vavr.collection.RedBlackTree.intersection(RedBlackTree.java:172)
	at io.vavr.collection.RedBlackTree.intersection(RedBlackTree.java:176)
```

### PR DESCRIPTION
**Pull request by roberterdin**
Bugfix in:
* RedBlackTreeModule->Node->deleteMin
* RedBlackTreeModule->Node->mergeEQ

Fixes #2098 

Thanks @danieldietrich for pointing out an error in 0a564fe and providing the unit tests.

### CODE REVIEW

File: vavr/src/main/java/io/vavr/collection/RedBlackTree.java [hunk 1]
```diff
@@ -744,7 +739,7 @@ private static boolean isRed(RedBlackTree<?> tree) {
                 return new Node<>(RED, n1.blackHeight + 1, n1, m, t2, n1.empty);
             } else if (isRed(n1.left)) {
                 final Node<T> node = new Node<>(BLACK, n1.blackHeight, n1.right, m, t2, n1.empty);
-                return new Node<>(RED, n1.blackHeight, Node.color(n1.left, BLACK), n1.value, node, n1.empty);
+                return new Node<>(RED, n1.blackHeight + 1, Node.color(n1.left, BLACK), n1.value, node, n1.empty);
```
Comment (danieldietrich) [inline vavr/src/main/java/io/vavr/collection/RedBlackTree.java]: Awesome! 🎉

**Comment by danieldietrich** [comment]
@roberterdin please don't mind, the JDK8 build is perfectly ok. We have some non-deterministic behavior regarding our JDK9 build. This is an open issue. I will merge your changes now.
